Batch 2 Updates
kbaseapps/kb_fastqc pull request #32
Opened 2019-04-18 20:25 UTC by mclark58

Edited display.yaml file to reflect the documentation changes.

2019-04-18 20:29 UTC, mclark58 commented
@jayrbolton / @tianhao-gu Not really sure who to tag here. Please merge the PR and push to dev. I will do a final check and then let you know when it's ready to be pushed to prod. Thanks!

2019-04-18 20:40 UTC, jayrbolton requested changes
just a couple tags to close

2019-04-18 20:40 UTC, jayrbolton commented on ui/narrative/methods/runFastQC/display.yaml
> +      <li><b>Kmer Content:</b> displays relative K-mer (k=7) enrichment over the read length for the top six K-mers. More specifically, it measures the number of each 7-mer at each position in the li
Add closing `</ul>` tag here

2019-04-18 20:40 UTC, jayrbolton commented on ui/narrative/methods/runFastQC/display.yaml
> +    <p>The HTML report includes results from multiple modules that were run by FastQC, and provides a quick assessment of the quality of the results labeled as normal (green checkmark), slightly abno
Add closing `</p>` tag here

2019-04-23 19:47 UTC, merged

2019-04-23 20:08 UTC, jayrbolton commented
lol yall never closed the tags

2019-04-23 20:10 UTC, jayrbolton commented
nvm i see paramvir did it on master.